export default class TadarabFBPixel {
    constructor() {}
    eventHandler(eventName, customData){
        this.eventName = eventName;
        // check if the event ID manually set, if not get it from cookies 
        if(!this.eventIdAlreadyExists){
            //get the event ID from cookies, which is generated by PHP 
            let eventIdCookieKey = this.eventName.toLowerCase() + '_event_id';
            this.eventId = this.getCookie(eventIdCookieKey);
        }
        let fbp = this.getCookie('_fbp');
        let fbc = this.getCookie('_fbc');
        fbq('track', eventName, customData, {eventID: this.eventId}, { fbp: fbp, fbc: fbc});
        // console.log('trackkk',fbq('track', eventName, customData, {eventID: this.eventId}, { fbp: fbp, fbc: fbc}));
        console.log(fbp,fbc,customData,eventName,this.eventId);
    }
    
    setEventId(eventId) {
        this.eventId = eventId;
        console.log('eventId',this.eventId,eventId);
        this.eventIdAlreadyExists = true;
    }    
    getEventId() { return this.eventId; }

    setEventName(eventName) { this.eventName = eventName; }    
    getEventName() { return this.eventName; }
    
    getCookie(name) {
        if (typeof document === 'undefined') {
            console.log('document is undefined.');return;
        }
        function escape(s) { return s.replace(/([.*+?\^$(){}|\[\]\/\\])/g, '\\$1'); }
        var match = document.cookie.match(RegExp('(?:^|;\\s*)' + escape(name) + '=([^;]*)'));
        return match ? match[1] : null;
    }
  }
